#!/bin/bash

pkill ros2
pkill rviz2
pkill aggregator_node
ps aux | grep "ros-args" | grep -v grep | awk '{ print "kill -9 ", $2 }' | sh
ps aux | grep component_container | grep -v grep | awk '{ print "kill -9 ", $2 }' | sh
ps aux | grep robot_state_publisher | grep -v grep | awk '{ print "kill -9 ", $2 }' | sh
ps aux | grep topic_tools/relay | grep -v grep | awk '{ print "kill -9 ", $2 }' | sh
ps aux | grep dummy_publisher.py | grep -v grep | awk '{ print "kill -9 ", $2 }' | sh
ps aux | grep python3 | grep rqt_reconfigure | grep -v grep | awk '{ print "kill -9 ", $2 }' | sh
ps aux | grep python3 | grep web_server | grep -v grep | awk '{ print "kill -9 ", $2 }' | sh
ps aux | grep python3 | grep rosbridge_websocket | grep -v grep | awk '{ print "kill -9 ", $2 }' | sh
ps aux | grep python3 | grep autoware_launch | grep -v grep | awk '{ print "kill -9 ", $2 }' | sh
ps aux | grep python3 | grep reproducer.py | grep -v grep | awk '{ print "kill -9 ", $2 }' | sh
ps aux | grep python3 | grep replayer.py | grep -v grep | awk '{ print "kill -9 ", $2 }' | sh
ps aux | grep ros2 | grep bag | grep -v grep | awk '{ print "kill -9 ", $2 }' | sh
