#!/usr/bin/env bash

VEHICLE_MODEL="lexus"
SENSOR_MODEL="aip_xx1"

if [ $1 ]; then
    # xx1
    if [ "$2" == "lexus" ]; then
        VEHICLE_MODEL="lexus"
        SENSOR_MODEL="aip_xx1"
    elif [ "$2" == "jpntaxi" ]; then
        VEHICLE_MODEL="jpntaxi"
        SENSOR_MODEL="aip_xx1"
        # x1
    elif [ "$2" = "eva" ]; then
        VEHICLE_MODEL="ymc_golfcart_proto2"
        SENSOR_MODEL="aip_x1"
        # x2
    elif [ "$2" = "gsm8" ]; then
        VEHICLE_MODEL="gsm8"
        SENSOR_MODEL="aip_x2"
        # s1
    elif [ "$2" = "crow" ]; then
        VEHICLE_MODEL="crow"
        SENSOR_MODEL="crow_sensor"
        # tutorial
    elif [ "$2" = "sample_vehicle" ]; then
        VEHICLE_MODEL="sample_vehicle"
        SENSOR_MODEL="sample_sensor_kit"
        # awsim
    elif [ "$2" = "awsim" ]; then
        VEHICLE_MODEL="sample_vehicle"
        SENSOR_MODEL="awsim_sensor_kit"
    fi

    echo "vehicle model is "$VEHICLE_MODEL
    echo "sensor model is "$SENSOR_MODEL

    ros2 launch scenario_test_runner scenario_test_runner.launch.py scenario:=$1 sensor_model:=$SENSOR_MODEL vehicle_model:=$VEHICLE_MODEL record:=false initialize_duration:=60 architecture_type:=awf/universe/20230906

else
    echo "No scenario file is given."
fi
